# Generated by Django 2.1.4 on 2018-12-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('nota1', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nota2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nota3', models.DecimalField(decimal_places=1, max_digits=3)),
                ('media', models.DecimalField(decimal_places=1, max_digits=3)),
                ('idade', models.IntegerField()),
                ('obs', models.TextField()),
            ],
        ),
    ]
